<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-30T06:55:09 GMT" name="Default suite" finished-at="2024-04-30T06:55:09 GMT" duration-ms="59">
    <groups>
    </groups>
    <test started-at="2024-04-30T06:55:09 GMT" name="Default test" finished-at="2024-04-30T06:55:09 GMT" duration-ms="59">
      <class name="testngScripts.ExternalDataDrivenExcel">
        <test-method is-config="true" signature="initSetup()[pri:0, instance:testngScripts.ExternalDataDrivenExcel@732c2a62]" started-at="2024-04-30T06:55:09 GMT" name="initSetup" finished-at="2024-04-30T06:55:09 GMT" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initSetup -->
        <test-method signature="validLogin(java.lang.String, java.lang.String)[pri:0, instance:testngScripts.ExternalDataDrivenExcel@732c2a62]" started-at="2024-04-30T06:55:09 GMT" name="validLogin" data-provider="logindata" finished-at="2024-04-30T06:55:09 GMT" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Some DataProvider public java.lang.String testngScripts.ExternalDataDrivenExcel.readObjPath(java.lang.String) parameters unresolved:  at 0 type class java.lang.String
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Some DataProvider public java.lang.String testngScripts.ExternalDataDrivenExcel.readObjPath(java.lang.String) parameters unresolved:  at 0 type class java.lang.String

at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:219)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:144)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
      </class> <!-- testngScripts.ExternalDataDrivenExcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
